### PR TITLE
(KW-176) Refresh Wallet Map UI

### PR DESCRIPTION
**Pull request by shottah**
### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

- [x] Add Food Forest geo spacial polygon data into the map
- [x] Click Food Forest location marker to focus forest on map
- [x] Click filters to toggle Vendors / Forests
- [x] Toggle vendor list between grid mode and list mode based on sheet height
- [x] Fix search bar
- [x] Add button to center map on users location

### Other changes

_Describe any minor or "drive-by" changes here._

* Modified map sheet snap points
* Hardcoded geo spacial data from food forests into `geojson` format
* Moved `watchFetchVendor` to be dispatched by the `map` saga
   * This allows us to handle all `map` external fetches at the map level 
* Remove `branding` files from tracked changes.

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### CODE REVIEW

**Review by Nashmod — DISMISSED** [review]
Damn, that's hot. Reviewed. Good to go!

The only feedback is why have the grid mode? When the list is too small and goes into grid mode you will always only be able to see the first 4. I feel like it makes the app feel buggier then anything else. unless we make the vendors scrollable horizontally I don't see a need for grid mode. But that's just my opinion.

Also maybe after closing the food forest bottom info sheet in the map let the map zoom out back to the default zoom. It zooms in allot and it gets tedious having to zoom out everytime you click on a food forest.

If this is intended feel free to Merge! :D

**Comment by Nashmod** [comment]
> Damn, that's hot. Reviewed. Good to go!
> 
> The only feedback is why have the grid mode? When the list is too small and goes into grid mode you will always only be able to see the first 4. I feel like it makes the app feel buggier then anything else. unless we make the vendors scrollable horizontally I don't see a need for grid mode. But that's just my opinion.
> 
> Also maybe have the food forests zoom out back too default a after closing, the zoom in is allot and makes the user have to readjust after closing any food forest.
>
> If this is intended feel free to Merge! :D

**Comment by shottah** [comment]
Let's go back to only list view, we can think more about the experience here as it may require animation work.
@mrkp

**Comment by shottah** [comment]
Fix search bar width, make background grey to match design.

**Comment by shottah** [comment]
Make map filter buttons look good. Use icons. Follow design.

**Comment by shottah** [comment]
Add button to center map on user's location

**Review by Nashmod — APPROVED** [review]
"Cucumbers are my favorite fruit"
     - Nashmod

Approved, Merge!

**Pull request merged**
