### PR TITLE
feat: (KW 84) Add button to execute trade on the swap screen

### PR DESCRIPTION
**Pull request by shottah**
### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

Adds a button on the swap screen that is enabled when the assets are selected.
Ideally, this button requires more data to be enabled. This will be further worked on once Symmetric Dex gets back to us.

### Other changes

_Describe any minor or "drive-by" changes here._

Changed box elements to have flex grow so that the button is positioned at the bottom of the screen.

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

Author testing by launching the swap interface and selecting tokens.

### How others should test

_Does this need to be tested by QA in the next release cycle? If so please give a brief explanation of how to test these changes._

May require tester to clear their redux store before using the swap screen to ensure a clean redux store as the swap interface stores the selected tokens in redux.

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

Only introduces javascript changes, and is backwards compatible.

### CODE REVIEW

**Comment by Nashmod** [comment]
Tested. Button seems to be there on fresh install without selecting any tokens yet.

image

Layout does look good.

Is that the desired feature?

**Comment by shottah** [comment]
Button should be disabled unless both tokens are selected. Will take another look.

**Review by Nashmod — APPROVED** [review]
Tested and working. Do note it is only approved if it was intentional that with two tokens selected but the amount is 0 the button is still enabled. If that is the case, please merge.

**Comment by shottah** [comment]
No, you're right. That should not be the case

**Review by Nashmod — CHANGES_REQUESTED** [review]
Swap button enabled when ether one or both amounts are empty.

image

**Review by Nashmod — APPROVED** [review]

**Pull request merged**
