### PR TITLE
feat: (KW 134) Allow user to send/receive crypto payments in person

### PR DESCRIPTION
**Pull request by shottah**
### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

Allows the user to send crypto by scanning a QR code.
Allows the user to receive crypto by creating a QR code.

- [x] Clicking "Send" opens the scan interface
- [x] Clicking "Receive" opens the receive amount interface
- [x] Scanning a "Receive QR code" opens a non-editable confirmation dialog
- [x] Scanning an "Address QR code" opens an editable send amount interface

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

Unit tests pending.

### How others should test

_Does this need to be tested by QA in the next release cycle? If so please give a brief explanation of how to test these changes._

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### CODE REVIEW

**Comment by shottah** [comment]
https://user-images.githubusercontent.com/14793093/183726820-d4634745-e191-4621-af91-dfb6db13d2de.mp4

**Review by Nashmod — CHANGES_REQUESTED** [review]
As you can see below I was able to send and receive payments. The issue comes where for some reason the recipient on the senders side always refers to Matthew.

Also it was almost impossible to test with android cause the app kept crashing due to some sort of memory leak issue.

image

image

**Comment by shottah** [comment]
Haha my bad. I forgot to change that. Good job for catching this! I'll submit an update in an hour or two.

**Comment by shottah** [comment]
Can you provide some additional context as to the crashes on Android? When does the crash occur.

**Comment by Nashmod** [comment]
After further testing, I see my android app seems to be crashing from any screen in general ill have to do further testing. I keep getting a crash and then a leak canary heap dump notification. Since I have an android I can't test the scanning due to the crashes. As you saw in my screenshot I did get it to work a few times so. in the meantime you can fix the issue that your name is always the recipient Is always you. 

Do you have another way I can test? maybe with ios? I had an iPhone attached but it still runs in the emulator. Even when the emulator is closed.

**Comment by shottah** [comment]
To run from iphone, you need to build from xcode while selecting your physical device as the target build device

**Comment by Nashmod** [comment]
Gotcha, ill do that monday!

**Comment by shottah** [comment]
@Nashmod ready for review again.

**Pull request merged**
