### PR TITLE
(retro) Add documentation on credentials and configurations

### PR DESCRIPTION
**Pull request by shottah**
### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

Indicate to all developers on the team the required credentials and secrets used in the app.

### CODE REVIEW

**Comment by shottah** [comment]
Let me know if this is sufficient, or what additional information you would like to see.

**Comment by Nashmod** [comment]
I like it, its only missing the part about the codepush key for android, that needs to be in the strings.xml file for the codepush updates to be looked up when the app is launched that cant be encrypted as its not a file.

Maybe also a little more of a detailed explanation of how to specify an environment when archiving with code.
I might be a little confused as i have never had different environments to archive so maybe a small explanation on how to do that. I think that should be all.

**Comment by shottah** [comment]
@Nashmod could you update the document with that information about codepush on android? I haven't done it myself.

Archiving different environment setups is a matter of using a different xcode scheme. You can read more about schemes, but I don't think it's necessary to put here as it's not specific to our project. Do you think it is worth putting in?

**Review by Nashmod — APPROVED** [review]
Looks good! Ill make another pr for me to change the android side!

**Comment by shottah** [comment]
@Nashmod where is the push to update the `strings.xml`, could you update the readme created here to indicate the information missing (per your first comment)?

**Pull request merged**
